<a href="https://colab.research.google.com/github/Pratik0124/Collab/blob/main/Lab1_Aiml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
from google.colab import files

uploaded = files.upload()

# Jo bhi CSV file upload hui hai, uska naam automatically le lega
filename = list(uploaded.keys())[0]

csv1 = pd.read_csv(filename)

csv1

Saving IPL_Kaggle_dataset.csv to IPL_Kaggle_dataset.csv

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [7]:
csv1.shape

(10, 9)

In [8]:
csv1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10 non-null     int64
 1   city            10 non-null     object
 2   team1           10 non-null     object
 3   team2           10 non-null     object
 4   toss_winner     10 non-null     object
 5   toss_decision   10 non-null     object
 6   winner          10 non-null     object
 7   win_by_runs     10 non-null     int64
 8   win_by_wickets  10 non-null     int64
dtypes: int64(3), object(6)
memory usage: 852.0+ bytes

In [9]:
csv1.head() #few rows from top

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [10]:
csv1.head().shape

(5, 9)

In [11]:
csv1.head(3) #3 rows from top

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10

In [12]:
csv1.tail() #few rows from bottom

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [13]:
csv1.tail(3) #3 rows from bottom

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [14]:

csv1.describe() # statisticalvalues for numeric values column

             id  win_by_runs  win_by_wickets
count  10.00000    10.000000       10.000000
mean    5.50000    14.700000        4.800000
std     3.02765    31.087868        3.823901
min     1.00000     0.000000        0.000000
25%     3.25000     0.000000        1.000000
50%     5.50000     0.000000        5.000000
75%     7.75000    11.250000        7.750000
max    10.00000    97.000000       10.000000

In [15]:
csv1['city'] #show a perticular column

0    Hyderabad
1         Pune
2       Rajkot
3       Indore
4    Bangalore
5    Hyderabad
6       Mumbai
7       Indore
8         Pune
9       Mumbai
Name: city, dtype: object

In [16]:
csv1['city'][5] #show a perticular column with perticular row

'Hyderabad'

In [17]:
csv1['city'][5]=0 #change a perticular column & perticular row's value with warning.original file wont be

/tmp/ipykernel_1881/221522474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv1['city'][5]=0 #change a perticular column & perticular row's value with warning.original file wont be

In [18]:
csv1

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [19]:
csv1.to_csv('matches_1.csv') #create a new file with changed data

In [20]:
csv1.index #info about indexes

RangeIndex(start=0, stop=10, step=1)

In [21]:
csv1.columns

Index(['id', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision',
       'winner', 'win_by_runs', 'win_by_wickets'],
      dtype='object')

In [22]:
csv1.T #rows and columns will get exchanged

,0,1,2,3,4,5,6,7,8,9
id,1,2,3,4,5,6,7,8,9,10
city,Hyderabad,Pune,Rajkot,Indore,Bangalore,0,Mumbai,Indore,Pune,Mumbai
team1,Sunrisers Hyderabad,Mumbai Indians,Gujarat Lions,Rising Pune Supergiant,Royal Challengers Bangalore,Gujarat Lions,Kolkata Knight Riders,Royal Challengers Bangalore,Delhi Daredevils,Sunrisers Hyderabad
team2,Royal Challengers Bangalore,Rising Pune Supergiant,Kolkata Knight Riders,Kings XI Punjab,Delhi Daredevils,Sunrisers Hyderabad,Mumbai Indians,Kings XI Punjab,Rising Pune Supergiant,Mumbai Indians
toss_winner,Royal Challengers Bangalore,Rising Pune Supergiant,Kolkata Knight Riders,Kings XI Punjab,Royal Challengers Bangalore,Sunrisers Hyderabad,Mumbai Indians,Royal Challengers Bangalore,Rising Pune Supergiant,Mumbai Indians
toss_decision,field,field,field,field,bat,field,field,bat,field,field
winner,Sunrisers Hyderabad,Rising Pune Supergiant,Kolkata Knight Riders,Kings XI Punjab,Royal Challengers Bangalore,Sunrisers Hyderabad,Mumbai Indians,Kings XI Punjab,Delhi Daredevils,Mumbai Indians
win_by_runs,35,0,0,0,15,0,0,0,97,0
win_by_wickets,0,7,10,6,0,9,4,8,0,4

In [23]:
csv1.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [24]:
csv1.sort_index(axis=0,ascending = False) #reverse order index axix=0 is row and axis=1 is column

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0

In [25]:
csv1.sort_index(axis=1,ascending = False) #reverse order column

,winner,win_by_wickets,win_by_runs,toss_winner,toss_decision,team2,team1,id,city
0,Sunrisers Hyderabad,0,35,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Sunrisers Hyderabad,1,Hyderabad
1,Rising Pune Supergiant,7,0,Rising Pune Supergiant,field,Rising Pune Supergiant,Mumbai Indians,2,Pune
2,Kolkata Knight Riders,10,0,Kolkata Knight Riders,field,Kolkata Knight Riders,Gujarat Lions,3,Rajkot
3,Kings XI Punjab,6,0,Kings XI Punjab,field,Kings XI Punjab,Rising Pune Supergiant,4,Indore
4,Royal Challengers Bangalore,0,15,Royal Challengers Bangalore,bat,Delhi Daredevils,Royal Challengers Bangalore,5,Bangalore
5,Sunrisers Hyderabad,9,0,Sunrisers Hyderabad,field,Sunrisers Hyderabad,Gujarat Lions,6,0
6,Mumbai Indians,4,0,Mumbai Indians,field,Mumbai Indians,Kolkata Knight Riders,7,Mumbai
7,Kings XI Punjab,8,0,Royal Challengers Bangalore,bat,Kings XI Punjab,Royal Challengers Bangalore,8,Indore
8,Delhi Daredevils,0,97,Rising Pune Supergiant,field,Rising Pune Supergiant,Delhi Daredevils,9,Pune
9,Mumbai Indians,4,0,Mumbai Indians,field,Mumbai Indians,Sunrisers Hyderabad,10,Mumbai

In [26]:
csv2=csv1

In [27]:
csv2['city'][0]="prayagraj"

/tmp/ipykernel_1881/1436405055.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv2['city'][0]="prayagraj"
/tmp/ipykernel_1881/1436405055.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv2['city'][0]="prayagraj"

In [28]:
csv2.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [29]:
csv1.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [30]:
csv3=csv1.copy()

In [31]:
csv3['city'][1]='GreNo'

/tmp/ipykernel_1881/3909947299.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv3['city'][1]='GreNo'
/tmp/ipykernel_1881/3909947299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv3['city'][1]='GreNo'

In [32]:
csv1.head() #no change in original file csvl

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [33]:
csv3.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,GreNo,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [34]:
csv2.loc[3,'city']='nainital'

In [35]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [36]:
csv2[0]='pooja'

In [37]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [38]:
csv2. drop(5)

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [39]:
csv2.drop(0,axis=1)

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [40]:
csv2.loc[[3,4],['city','winner']]

        city                       winner
3   nainital              Kings XI Punjab
4  Bangalore  Royal Challengers Bangalore

In [41]:
csv2.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja

In [42]:
csv2.loc[: ,['city','winner']]

        city                       winner
0  prayagraj          Sunrisers Hyderabad
1       Pune       Rising Pune Supergiant
2     Rajkot        Kolkata Knight Riders
3   nainital              Kings XI Punjab
4  Bangalore  Royal Challengers Bangalore
5          0          Sunrisers Hyderabad
6     Mumbai               Mumbai Indians
7     Indore              Kings XI Punjab
8       Pune             Delhi Daredevils
9     Mumbai               Mumbai Indians

In [43]:
csv2.loc[[3,4],:]

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja

In [44]:
csv2.loc[(csv2['toss_decision']=='field')]

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [45]:
csv2.loc[(csv2['toss_decision']=='field')&(csv2['city']=='Mumbai')]

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [46]:
csv2.iloc[0,6]

'Sunrisers Hyderabad'

In [47]:
csv2.iloc[[0,6],[2,5]]

                   team1 toss_decision
0    Sunrisers Hyderabad         field
6  Kolkata Knight Riders         field

In [48]:
csv2.head(3)

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja

In [49]:
csv2.drop([1])

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [50]:
csv2.drop([0],axis=1)

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [51]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [52]:
#csv2=csv2.drop([0],axis=1) #column 0 get deleted permanently from original file. (1st method )
csv2.drop([0],axis=1,inplace=True) # column 0 get deleted permanently from original file.(2nd method)

In [53]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [54]:
csv2.drop(['winner','toss_decision'],axis=1,inplace=True)

In [55]:
csv2.drop([2,4],axis=0,inplace=True)

In [56]:
csv2

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6
5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,0,4

In [57]:
csv2.reset_index()

,index,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0
1,1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7
2,3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6
3,5,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9
4,6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0,4
5,7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,0,8
6,8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,97,0
7,9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,0,4

In [58]:
csv2.reset_index(drop=True,inplace=True)

In [59]:
csv2.head(4)

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7
2,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6
3,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9

In [60]:
csv2['win_by_runds']=None

In [61]:
csv2

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets,win_by_runds
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0,None
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7,None
2,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6,None
3,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9,None
4,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0,4,None
5,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,0,8,None
6,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,97,0,None
7,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,0,4,None

In [62]:
csv2.isnull()

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets,win_by_runds
0,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,True

In [63]:
csv2['win_by_runs'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: win_by_runs, dtype: bool

In [64]:
csv2['win_by_runs']=99

In [65]:
csv2

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets,win_by_runds
0,1,prayagraj,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,99,0,None
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,99,7,None
2,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,99,6,None
3,6,0,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,99,9,None
4,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,99,4,None
5,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,99,8,None
6,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,99,0,None
7,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,99,4,None

In [66]:
df=pd.DataFrame({"name":['Alfred','batman','Catwoman'],
                 "toy":[np.nan,'batmobile','Bullwhip'],
                 "born":[pd.NaT,pd.Timestamp("1940-04-25"),
                         pd.NaT]})

In [67]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    batman  batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [68]:
df.dropna()

     name        toy       born
1  batman  batmobile 1940-04-25

In [69]:
df.dropna(how='all')

       name        toy       born
0    Alfred        NaN        NaT
1    batman  batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [70]:
df1 =pd.DataFrame({"name" : [ 'Alfred','batman','Catwoman'] ,
                 " toy ": [np.nan, np.nan,np.nan] ,
                 "born": [pd.NaT,pd.Timestamp("1940-04-25"),
                         pd.NaT]})

In [71]:
df1

       name   toy        born
0    Alfred    NaN        NaT
1    batman    NaN 1940-04-25
2  Catwoman    NaN        NaT

In [72]:
df1.dropna(how='all',axis=1)

       name       born
0    Alfred        NaT
1    batman 1940-04-25
2  Catwoman        NaT

In [73]:
df1

       name   toy        born
0    Alfred    NaN        NaT
1    batman    NaN 1940-04-25
2  Catwoman    NaN        NaT

In [74]:
df2 =pd.DataFrame({"name" : [np.nan,'batman','Catwoman'] ,
                 " toy ": [np.nan,'Batmobile','Bullwhip'] ,
                 "born": [pd.NaT,pd.Timestamp("1940-04-25"),
                         pd.NaT]})

In [75]:
df2

       name       toy        born
0       NaN        NaN        NaT
1    batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [76]:
df2.dropna(how='all')

       name       toy        born
1    batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [81]:
df3 =pd.DataFrame({"name" : [np.nan,'Batman','Alfred'],
                 "toy": [np.nan,'Batmobile','Bullwhip'] ,
                 "born": [pd.NaT,pd.Timestamp("1940-04-25"),
                         pd.NaT]})

In [77]:
df2

       name       toy        born
0       NaN        NaN        NaT
1    batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [84]:
df3.drop_duplicates(subset=['name'])

     name        toy       born
0     NaN        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [85]:
df3.drop_duplicates(subset=['name'],keep='last')

     name        toy       born
0     NaN        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [87]:
df3.drop_duplicates(subset=['name'],keep= False)

     name        toy       born
0     NaN        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [88]:
df3.shape

(3, 3)

In [89]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [15]:
import pandas as pd

In [23]:
da

NameError: name 'da' is not defined