<a href="https://colab.research.google.com/github/Pratik0124/Collab/blob/main/Multiple_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving multiple.homeprices.csv to multiple.homeprices.csv

In [3]:
import pandas as pd

df = pd.read_csv('multiple.homeprices.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Data Preprocessing: Fill NA values with median value of a
column

In [4]:
df.bedrooms.median()

4.0

In [5]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

y = mx1 + mx2+ mx3+ b

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

np.float64(221323.00186540396)

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [10]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [11]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [12]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])